# fly.toml app configuration file generated for mediapi on 2023-08-03T15:54:55-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mediapi"
primary_region = "gru"

[build]
  image = "flyio/hellofly:latest"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
